-- MySQL Script generated by MySQL Workbench
-- mié 03 oct 2018 13:57:32 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`nursinghome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nursinghome` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nursinghome` (
  `idnursinghome` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnursinghome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`branches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`branches` (
  `idbranches` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `total_rooms` INT NOT NULL,
  `available_rooms` INT NOT NULL,
  PRIMARY KEY (`idbranches`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nursinghome_has_branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nursinghome_has_branches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nursinghome_has_branches` (
  `nursinghome_idnursinghome` INT NOT NULL,
  `branches_idbranches` INT NOT NULL,
  PRIMARY KEY (`nursinghome_idnursinghome`, `branches_idbranches`),
  INDEX `fk_nursinghome_has_branches_branches1_idx` (`branches_idbranches` ASC),
  INDEX `fk_nursinghome_has_branches_nursinghome_idx` (`nursinghome_idnursinghome` ASC),
  CONSTRAINT `fk_nursinghome_has_branches_nursinghome`
    FOREIGN KEY (`nursinghome_idnursinghome`)
    REFERENCES `mydb`.`nursinghome` (`idnursinghome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nursinghome_has_branches_branches1`
    FOREIGN KEY (`branches_idbranches`)
    REFERENCES `mydb`.`branches` (`idbranches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
