-- MySQL Script generated by MySQL Workbench
-- jue 18 oct 2018 18:30:26 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NursingHomes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NursingHomes` ;

-- -----------------------------------------------------
-- Schema NursingHomes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NursingHomes` DEFAULT CHARACTER SET utf8 ;
USE `NursingHomes` ;

-- -----------------------------------------------------
-- Table `NursingHomes`.`nursinghome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NursingHomes`.`nursinghome` ;

CREATE TABLE IF NOT EXISTS `NursingHomes`.`nursinghome` (
  `idnursinghome` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnursinghome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NursingHomes`.`branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NursingHomes`.`branches` ;

CREATE TABLE IF NOT EXISTS `NursingHomes`.`branches` (
  `idbranches` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `total_rooms` INT NOT NULL,
  `available_rooms` INT NOT NULL,
  `nursinghome_idnursinghome` INT NOT NULL,
  PRIMARY KEY (`idbranches`, `nursinghome_idnursinghome`),
  INDEX `fk_branches_nursinghome_idx` (`nursinghome_idnursinghome` ASC),
  CONSTRAINT `fk_branches_nursinghome`
    FOREIGN KEY (`nursinghome_idnursinghome`)
    REFERENCES `NursingHomes`.`nursinghome` (`idnursinghome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;